apiVersion: v1
data:
  allowed: true
  enemies: aliens
  lives: 3
immutable: false
kind: ConfigMap
metadata:
  name: test-config-map
  namespace: default

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 9376
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ngnix
  name: test-deployment
  namespace: default
spec:
  minReadySeconds: 0
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ngnix
  template:
    metadata:
      labels:
        app: ngnix
      namespace: default
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        ports:
        - hostIP: 127.0.0.1
          protocol: TCP
        resources:
          limits:
            cpu: 1000m
            memory: 2000Mi
          requests:
            cpu: 500m
            memory: 256Mi
        volumeMounts:
        - mountPath: /etc/config
          name: config-vol
          readOnly: true
          subPath: ''
          subPathExpr: ''
        workingDir: /test-dir
      volumes:
      - configMap:
          name: log-config
          optional: false
          items:
          - key: log_level
            path: log_level.conf
        name: config-vol

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ngnix
  name: test-another-deployment
  namespace: default
spec:
  minReadySeconds: 0
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ngnix
  template:
    metadata:
      labels:
        app: ngnix
      namespace: default
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        ports:
        - hostIP: 127.0.0.1
          protocol: TCP
        resources:
          limits:
            cpu: 1000m
            memory: 2000Mi
          requests:
            cpu: 500m
            memory: 256Mi
        volumeMounts:
        - mountPath: /etc/config
          name: config-vol
          readOnly: true
          subPath: ''
          subPathExpr: ''
        workingDir: /test-dir
      volumes:
      - configMap:
          name: log-config
          optional: false
          items:
          - key: log_level
            path: log_level.conf
        name: config-vol

