apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ngnix
  name: test-deployment
  namespace: default
spec:
  minReadySeconds: 0
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ngnix
  template:
    metadata:
      labels:
        app: ngnix
      namespace: default
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        ports:
        - hostIP: 127.0.0.1
          protocol: TCP
        workingDir: /test-dir

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ngnix
  name: test-another-deployment
  namespace: default
spec:
  minReadySeconds: 0
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ngnix
  template:
    metadata:
      labels:
        app: ngnix
      namespace: default
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        ports:
        - hostIP: 127.0.0.1
          protocol: TCP
        workingDir: /test-dir

