name: Build and Publish Docs

on:
  pull_request:
    branches: [ main ]
    paths:
    - '**.fs'
    - '**.fsproj'
  workflow_dispatch:

env:
  config: Debug
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  dotnet_core_version: 6.0.x # The .NET SDK version to use

jobs:
  build-and-publish-docs:

    name: build-and-test-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Versions
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          3.1.x
          6.0.x

    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration $config --no-restore
    
    - name: Install tools
      run: dotnet tool restore
    
    - name: Generate docs
      run: dotnet fsdocs build --eval

    - name: Deploy docs 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: output # The folder the action should deploy.